(()=>{'use strict';
const lessons=window.MAINLINE, $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={active:0,answers:{},notes:{}};try{const x=JSON.parse(localStorage.getItem('ml-mainline-v1'));if(x&&Number.isInteger(x.active)&&x.active>=0&&x.active<12){state.active=x.active;for(const k of ['answers','notes'])if(x[k]&&typeof x[k]==='object'&&!Array.isArray(x[k]))state[k]=x[k];}}catch{}
const save=()=>{try{localStorage.setItem('ml-mainline-v1',JSON.stringify(state));$('#storage').textContent='';}catch{$('#storage').textContent='浏览器无法保存，请使用导出学习记录。';}};
const softmax=a=>{let m=Math.max(...a),e=a.map(x=>Math.exp(x-m)),s=e.reduce((a,b)=>a+b,0);return e.map(x=>x/s);};
const math={softmax,gradient:(w,r)=>{let loss=t=>[1,2,3].reduce((s,x)=>s+(t*x-3*x)**2,0)/3,g=28*(w-3)/3;return{gradient:g,next:w-r*g,before:loss(w),after:loss(w-r*g)};},confusion:t=>{let c={TP:0,FP:0,FN:0,TN:0};[.9,.8,.7,.4,.3,.1].forEach((p,i)=>{let y=[1,0,1,1,0,0][i];c[p>=t?(y?'TP':'FP'):(y?'FN':'TN')]++;});return c;}};window.MainlineExperiments=math;
const n=x=>Number(x).toFixed(2), bars=(labels,values)=>values.map((v,i)=>`<div class="barrow"><span>${labels[i]}</span><div class="track"><div class="bar" style="width:${100*v}%"></div></div><span>${n(v*100)}%</span></div>`).join('');
function experiment(id){let fields=[],draw;const range=(key,label,value,min,max,step=1)=>fields.push({key,label,value,min,max,step}),select=(key,label,choices)=>fields.push({key,label,choices});
if(id===0){range('x','苹果重量（千克）',2,0,5,.5);range('w','每千克价格',2,0,6,.5);range('b','固定费用',1,-5,5);draw=v=>`<p>${v.x} × ${v.w} + ${v.b} = <strong>${n(v.x*v.w+v.b)} 元</strong></p><p>你正在改规则并做预测；这还不是从数据自动训练。</p>`;}
if(id===1){range('w','更新前的单价',1,0,6,.1);range('r','学习率',.1,.01,.5,.01);draw=v=>{let a=math.gradient(v.w,v.r);return `<p>样本：1kg→3元，2kg→6元，3kg→9元</p><p>梯度 ${n(a.gradient)}；新单价 = ${n(v.w)} − ${v.r} × ${n(a.gradient)} = ${n(a.next)}</p><p>平均平方误差：${n(a.before)} → <strong>${n(a.after)}</strong>。${a.after>a.before?'步子太大，越调越差。':'这一步误差没有增加。'}</p><p>这是同一训练集上的一次更新，未证明新数据表现。</p>`;};}
if(id===2){range('t','判为正类的阈值',.5,0,1,.1);draw=v=>{let c=math.confusion(v.t);return `<p>六个预测分数：0.9、0.8、0.7、0.4、0.3、0.1<br>真实标签：1、0、1、1、0、0</p><p>命中 TP=${c.TP} · 误报 FP=${c.FP}<br>漏报 FN=${c.FN} · 正确排除 TN=${c.TN}</p><p>精确率：${c.TP+c.FP?n(c.TP/(c.TP+c.FP)):'无预测正类，不能计算'}；召回率：${n(c.TP/3)}</p>`;};}
if(id===3){range('x','查询向量横坐标',1,-1,1,.1);range('y','查询向量纵坐标',0,-1,1,.1);range('a','向东候选长度',1,1,2,.1);draw=v=>`<p>查询 [${v.x}, ${v.y}]</p><table><tr><th>候选坐标</th><th>点积</th></tr><tr><td>A [${v.a},0]</td><td>${n(v.x*v.a)}</td></tr><tr><td>B [0,1]</td><td>${n(v.y)}</td></tr><tr><td>C [-1,0]</td><td>${n(-v.x)}</td></tr></table><p>点积是对应坐标相乘再相加。这里是人工坐标，未学习语言含义；改变长度也会影响分数。</p>`;}
if(id===4){range('p','当前词位置（从0开始）',2,0,3);draw=v=>{let a=softmax([1,2,3,4].slice(0,v.p+1)),out=a.reduce((s,w,i)=>s+w*(i+1)*10,0);return bars(['词0','词1','词2','词3'],[...a,...Array(3-v.p).fill(0)])+`<p>分数 [1,2,3,4]，传递的值 [10,20,30,40]。当前及之前位置参与加权，后面位置权重为0。</p><p>加权结果：<strong>${n(out)}</strong>；这组分数是预设值，不是完整 Transformer。</p>`;};}
if(id===5){range('t','温度',1,.2,2,.1);draw=v=>bars(['候选A','候选B','候选C'],softmax([2,1,0].map(x=>x/v.t)))+'<p>固定原始分数 [2,1,0]。低温更集中，高温更分散；最高分候选不变，但采样时不一定选中它。概率不是事实正确率。</p>';}
if(id===6){select('s','预置响应',['字段完整但日期事实缺失','格式错误','缺少字段','编造日期']);draw=v=>{let samples=['{"amount":128,"date":null,"evidence":"单据金额128元"}','{"amount":128,','{"amount":128,"evidence":"单据金额128元"}','{"amount":128,"date":"2026-01-01","evidence":"单据金额128元"}'],raw=samples[+v.s],p;try{p=JSON.parse(raw);}catch{}let schema=p&&typeof p.amount==='number'&&Object.hasOwn(p,'date')&&typeof p.evidence==='string';return `<pre>${esc(raw)}</pre><p>语法：${p?'通过':'不通过'}；字段：${schema?'通过':'未通过'}。</p><p>${!schema?'修正结构后重新校验。':p.date===null?'日期明确未知；本业务要求补日期，暂停入账。':'原单据没有日期，这个日期没有证据，拒绝入账。'}</p>`;};}
if(id===7){range('i','问题与历史 token',512,0,4096,128);range('d','文档 token',2304,0,4096,128);range('o','输出预留 token',1024,128,2048,128);draw=v=>{let total=256+v.i+v.d+v.o;return `<p>256 + ${v.i} + ${v.d} + ${v.o} = <strong>${total}</strong> / 4096</p><p>${total>4096?'超出 '+(total-4096)+'，需要选择删减或拒绝策略。':'剩余 '+(4096-total)+'。预算合规仍不保证证据完整。'}</p>`;};}
if(id===8){range('t','候选过滤阈值',.7,0,1,.01);select('doc','选择回答依据',['现行政策','旧政策','无关文档']);draw=v=>{let docs=[['现行政策',.81,'普通订单7天'],['旧政策',.92,'旧版30天'],['无关文档',.5,'配送时间']],d=docs[+v.doc];return '<table><tr><th>文档</th><th>分数</th><th>保留？</th></tr>'+docs.map(d=>`<tr><td>${d[0]}</td><td>${d[1]}</td><td>${d[1]>=v.t?'是':'否'}</td></tr>`).join('')+`</table><p>${d[1]<v.t?'所选资料已被过滤，证据不足，应停止回答。':+v.doc===0?'当前普通订单可据此回答7天；仍需核对订单条件。':'所选资料不适用于当前普通订单，不能作为回答依据。'}</p>`;};}
if(id===9){select('op','提议操作',['读取 read','写入 write','删除 delete']);select('yes','是否明确批准该操作',['没有批准','已批准具体操作与对象']);draw=v=>`<p>门禁：<strong>${+v.op===0||+v.yes===1?'允许进入执行阶段':'拒绝'}</strong></p><p>${+v.op===0?'读取默认允许仅是教学简化；实际仍须校验身份与范围。':'写入或删除需要批准绑定具体对象和参数。'} 本页不执行真实操作。</p>`;}
if(id===10){select('s','观察到的缺口',['本周事实缺失','固定输出结构错误','稳定任务行为差距']);select('choice','优先考虑方案',['提示与确定性校验','版本化检索 RAG','评估微调']);draw=v=>{let expected=[1,0,2][+v.s];return `<p>${+v.choice===expected?'方案与这个预置缺口相符。':'这个方案没有优先针对当前缺口。'}</p><p>${['先提供当前有效证据，再测检索和答案是否正确。','先明确字段和失败协议，无需立即训练。','先有足量高质量样本、提示基线和独立验收集，再比较微调收益。'][+v.s]}</p>`;};}
if(id===11){select('m','预置结果模式',['全部回答','有证据才回答','全部拒答']);draw=v=>{let rows=[['现行退款期限',true],['配送范围',true],['发票规则',true],['旧版退款陷阱',true],['未公布优惠',false],['内部未授权价格',false]],m=+v.m,answered=rows.map((r,i)=>m===0||(m===1&&i<3)),correct=rows.map((r,i)=>answered[i]&&i<3),cited=rows.map((r,i)=>answered[i]&&i!==4),supported=rows.map((r,i)=>cited[i]&&i<3),count=a=>a.filter(Boolean).length;return `<table><tr><th>问题</th><th>可答</th><th>预置结果</th></tr>${rows.map((r,i)=>`<tr><td>${r[0]}</td><td>${r[1]?'是':'否'}</td><td>${answered[i]?(correct[i]?'答对，引用支持':'答错，引用不支持或缺失'):'拒答'}</td></tr>`).join('')}</table><p>可回答题答对：${count(correct)}/4；无答案题正确拒答：${rows.filter((r,i)=>!r[1]&&!answered[i]).length}/2。</p><p>引用支持：${count(cited)?count(supported)+'/'+count(cited):'无带引用回答，不可计算'}；无引用回答 ${answered.filter((a,i)=>a&&!cited[i]).length} 条。</p><p>所有结果标签均为预置，未调用模型；“有证据”模式仍误拒了第4题。</p>`;};}
$('#controls').innerHTML=fields.map(f=>`<label class="field"><span>${f.label} <output id="value-${f.key}"></output></span>${f.choices?`<select data-field="${f.key}">${f.choices.map((x,i)=>`<option value="${i}">${x}</option>`).join('')}</select>`:`<input data-field="${f.key}" type="range" value="${f.value}" min="${f.min}" max="${f.max}" step="${f.step}">`}</label>`).join('');
const update=()=>{let v={};document.querySelectorAll('[data-field]').forEach(e=>{v[e.dataset.field]=+e.value;if(e.type==='range')$('#value-'+e.dataset.field).textContent=e.value;});$('#output').innerHTML=draw(v);};$('#controls').addEventListener('input',update);update();}
const passed=l=>l.quizzes.every((q,i)=>state.answers[l.id+'-'+i]===q.answer);
function nav(){let week=0;$('#courseList').innerHTML=lessons.map(l=>{let h=l.week!==week?`<h2>第${l.week}周 · ${['模型如何学习','语言模型如何工作','把模型接入资料','选择方案与验收'][l.week-1]}</h2>`:'';week=l.week;return h+`<button data-lesson="${l.id}" ${l.id===state.active?'aria-current="page"':''}>${l.id+1}. ${esc(l.title)}${passed(l)?' ✓':''}</button>`;}).join('');$('#progress').textContent=`判断题通过 ${lessons.filter(passed).length}/12课 · 项目请按标准自查`;
 document.querySelectorAll('[data-lesson]').forEach(e=>e.onclick=()=>open(+e.dataset.lesson));}
function menu(show){$('#syllabus').classList.toggle('open',show);document.body.classList.toggle('menu-open',show);$('#veil').hidden=!show;$('#menu').setAttribute('aria-expanded',String(show));if(show)$('#closeMenu').focus();else $('#menu').focus();}
function open(id,scroll=true){state.active=id;save();menu(false);let l=lessons[id];$('#location').textContent=`第${l.week}周 · ${id+1}/12`;$('#readerTitle').textContent=l.title;$('#previous').disabled=id===0;$('#next').disabled=id===11;$('#continue').disabled=id===11;$('#continue').textContent=id===11?'主线已到最后一课':'继续下一课 →';
$('#lesson').innerHTML=`<span class="kicker">第${l.week}周 · 第${id+1}课</span><h1>${esc(l.title)}</h1><p class="lead">${esc(l.goal)}</p><section class="scene"><h2>从这件事开始</h2><p>${esc(l.scene)}</p></section><h2>把过程讲清楚</h2><ol class="mechanism">${l.mechanism.map(s=>`<li><h3>${esc(s.title)}</h3><p>${esc(s.body)}</p></li>`).join('')}</ol><p class="boundary">${esc(l.boundary)}</p><section class="experiment"><h2>亲手改一次，看看结果</h2><p>${esc(l.experiment.instruction)}</p><p><strong>先预测：</strong>${esc(l.experiment.predict)}</p><div id="controls" class="fields"></div><div id="output" class="output" aria-live="polite"></div><p>${esc(l.experiment.observe)}</p><label>记录你的预测与观察<textarea data-note="observation" placeholder="我原来以为……改变参数后……原因是……"></textarea></label></section><section class="misconception"><h2>一个容易混淆的地方</h2><blockquote>${esc(l.misconception.claim)}</blockquote><p>${esc(l.misconception.correction)}</p></section><section class="quiz"><h2>换个场景，你能判断吗？</h2>${l.quizzes.map((q,i)=>`<fieldset><legend>${i+1}. ${esc(q.prompt)}</legend><div class="options">${q.options.map((o,j)=>`<button data-q="${i}" data-a="${j}" aria-pressed="false">${esc(o.text)}</button>`).join('')}</div><p class="feedback" id="feedback-${i}" role="status"></p></fieldset>`).join('')}</section><section class="project"><h2>留下一份能检查的成果</h2><p>${esc(l.project.task)}</p><ul>${l.project.deliverables.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>自查标准</h3><ul>${l.project.criteria.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><label>我的交付草稿<textarea data-note="project" placeholder="填写你的方案、数字、证据和待验证项"></textarea></label><p class="save-status">自动保存在本浏览器。填写不等于通过验收。</p><details><summary>需要时看一个起步示例</summary><p>${esc(l.project.example)}</p></details></section><details class="deep"><summary>深入了解 · 推导、代码与配套课</summary><p>${esc(l.deep.intro)}</p><ul>${l.deep.questions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p>带着以上问题进入知识库，查看详细推导、源码注释与 Python 练习：</p><ul>${l.deep.lessonIds.map(i=>`<li><a href="library.html#lesson=${i}">第${i+1}课 · ${esc(window.MAINLINE_LIBRARY[i])}</a></li>`).join('')}</ul><p>原项目：<a href="https://github.com/samitmohan/ML">samitmohan/ML</a>。应用工程扩展与原仓库实现范围分开标注。</p></details>`;
experiment(id);function answer(i,a){let q=l.quizzes[i];document.querySelectorAll(`[data-q="${i}"]`).forEach(e=>e.setAttribute('aria-pressed',String(+e.dataset.a===a)));let out=$('#feedback-'+i);out.textContent=q.options[a].feedback;out.dataset.correct=String(a===q.answer);}
document.querySelectorAll('[data-q]').forEach(e=>e.onclick=()=>{let i=+e.dataset.q,a=+e.dataset.a;state.answers[id+'-'+i]=a;answer(i,a);save();nav();});l.quizzes.forEach((q,i)=>{let a=state.answers[id+'-'+i];if(Number.isInteger(a)&&a>=0&&a<3)answer(i,a);});document.querySelectorAll('[data-note]').forEach(e=>{let key=id+'-'+e.dataset.note;e.value=typeof state.notes[key]==='string'?state.notes[key]:'';e.oninput=()=>{state.notes[key]=e.value;save();};});nav();if(scroll)$('#lesson').scrollIntoView({behavior:'instant'});}
$('#menu').onclick=()=>{if(matchMedia('(max-width:760px)').matches)menu(true);else $('#courseList button[aria-current]').focus();};$('#closeMenu').onclick=()=>menu(false);$('#veil').onclick=()=>menu(false);document.addEventListener('keydown',e=>{if(!$('#syllabus').classList.contains('open'))return;if(e.key==='Escape')menu(false);if(e.key==='Tab'){let a=[...$('#syllabus').querySelectorAll('button,a')],first=a[0],last=a.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});$('#previous').onclick=()=>open(Math.max(0,state.active-1));$('#next').onclick=$('#continue').onclick=()=>open(Math.min(11,state.active+1));$('#export').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='四周学习记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};open(state.active,false);
})();
