from pathlib import Path
p=Path('app.js');s=p.read_text()
s=s.replace('function open(id,scroll=true){clearInterval(timer);','function open(id,scroll=true){window.LabUI?.unmount();clearInterval(timer);')
s=s.replace('${state.passed.length} / 16 小测通过','${state.passed.length} / ${lessons.length} 小测通过').replace("$('#progress').value=state.passed.length;","$('#progress').max=lessons.length;$('#progress').value=state.passed.length;")
s=s.replace('id===15','id===lessons.length-1').replace('${id+1} / 16 课','${id+1} / ${lessons.length} 课')
s=s.replace('<label for="note">','<section class="panel" id="labHost"></section><label for="note">')
s=s.replace("$('#prev').disabled=id===0;","window.LabUI?.mount(l,$('#labHost'));$('#prev').disabled=id===0;")
s=s.replace("const term=$('#search').value.toLowerCase();", "const term=$('#search').value.toLowerCase(),scope=$('#courseScope').value;")
s=s.replace("lessons.filter(l=>(!$('#review')", "lessons.filter(l=>(scope==='all'||(scope==='intro'?l.id<16:l.id>=16))&&(!$('#review')")
s=s.replace("$('#search').oninput=catalog;", "$('#search').oninput=catalog;$('#courseScope').onchange=catalog;")
s=s.replace("$('#files').innerHTML=files.filter(f=>f.toLowerCase().includes(term)).map(f=>`<a target=", "$('#files').innerHTML=files.filter(f=>f.toLowerCase().includes(term)).map(f=>`<p class=\"source-map-row\">${window.COURSE.fileMap?.[f]?.map(id=>`<button class=\"source-lesson\" data-id=\"${id}\">第${id+1}课</button>`).join('')||''}<a target=")
s=s.replace('${esc(f)}</a>`).join', '${esc(f)}</a></p>`).join')
s=s.replace("$('#catalog').onclick=e=>", "$('#files').onclick=e=>{const b=e.target.closest('[data-id]');if(b)open(+b.dataset.id)};$('#catalog').onclick=e=>")
p.write_text(s)
p=Path('index.html');s=p.read_text().replace('中文导读 · 16课','项目学习路线 · 48课').replace('max="16"','max="48"')
s=s.replace('<label for="search">','<label for="courseScope">学习路线</label><select id="courseScope"><option value="all">全部48课</option><option value="intro">先建立直觉 · 16课</option><option value="project">深入项目 · 32课</option></select><p class="muted">先读1–16课，再用17–48课深入模块。课程编号保留原有进度。</p><label for="search">')
s=s.replace('核心导读，不是逐文件完整课程。演示在浏览器本地计算；源码链接需联网。小测通过不代表独立实操已完成。','涵盖仓库主要模块；源码索引区分精讲入口与拓展文件。小测、浏览器练习和完整模型训练是三种不同的验证。')
s=s.replace('<script src="app.js"></script>','<script src="runner.js"></script><script src="lab-ui.js"></script><script src="app.js"></script>')
s=s.replace('</style>','''.lab-output,#labHost pre{white-space:pre-wrap;overflow-wrap:anywhere;padding:16px;background:#edf1e9;border-radius:8px;font-size:14px;max-height:380px;overflow:auto}.lab-controls{margin-top:16px}.lab-controls button{font-size:14px}.lab-proof{font-weight:600;color:var(--green)}#courseScope{width:100%;padding:10px;background:white;border:1px solid var(--line);border-radius:8px}.source-map-row{border-bottom:1px solid var(--line);padding:10px 0}.source-lesson{padding:3px 7px;min-height:36px;font-size:12px}#labHost{scroll-margin-top:100px}
</style>''');p.write_text(s)
